comment: # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

codecov:
  bot: "codecov-io"
  disable_default_path_fixes: no
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 80%   # the required coverage value
        threshold: 0.03%  # the leniency in hitting the target
    patch:
      default:
        threshold: 0.03%
        target: 90%
